config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "home" => "homes#show"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, {presence: true}
  validates :body, {presence: true, length: {maximum:200}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, {uniqueness: true, length: {in: 2..20}}
  validates :introduction, {length: {maximum:50}}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :introduction, :profile_image_id])
    
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @book = Book.new
  end
  
  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      flash[:notice] = "successfully."
      redirect_to book_path(book)
    else
      flash[:not] = "error."
      @book = book
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  
  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
    #@book = Book.find(params[:id])
    #@user = @book.user
  end
  
  def show
    @book2 = Book.find(params[:id])
    @user = @book2.user
    @book = Book.new
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
    else
      redirect_to books_path
    end 
    
  end
  
  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "successfully."
      redirect_to book_path(book)
    else
    @book = book
    flash[:not] = "error."
    render :edit

      
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    
  end  
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end
  
  def about
    
  end
  
  def show
  
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
 
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
    else
      redirect_to user_path(current_user)
    end 

    
  end
  
  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "successfully."
      redirect_to user_path(user.id)
    else
      @user = user
      flash[:not] = "error."
      render :edit
  
  
    end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2>New book</h2>
<%= form_with model: book, local:true do |f| %>
<div class='form-group'>
  <p>Title</p>
  <%= f.text_field :title %>
</div>
<div>
  <p></p>Opinion</p>
  <%= f.text_area :body %>
</div>
<div class="mt-3">
  <%= f.submit "Create Book", class: "btn btn-success" %>
</div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class="container mx-auto">
  <h2>Editing Book</h2>
  <%= form_with model: @book, local:true do |f| %>
  <div class='form-group'>
    <p>Title</p>
    <%= f.text_field :title %>
  </div>
  <div>
    <p></p>Opinion</p>
    <%= f.text_area :body %>
  </div>
  <div class="mt-3">
    <%= f.submit "Update Book", class: "btn btn-success" %>
  </div>
  <% end %>
  
    <%= link_to "Show",  book_path(@book) %>
    |
    <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-o">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user-info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class='table table-hover table-invers'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |books| %>
          <tr>
            <td>
              <%= link_to user_path(books.user.id), method: :get do %>
                <%= attachment_image_tag books.user, :profile_image_id, :fill, 30, 30, fallback: "no_image.jpg" %>
              <% end %>
            </td>
        
            <td><%= link_to books.title, book_path(books) %></td>
           
            <td><%= books.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto mt-5">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/new.html.erb
<%= render 'books/form', book: @book %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user-info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          
          <td>
            <%= link_to user_path(@book2.user), method: :get do %>
            <%= attachment_image_tag @book2.user, :profile_image_id, :fill, 30, 30, fallback: "no_image.jpg" %>
            <br>
            <%= @book2.user.name %>
            <% end %>
          </td>
          
          <td>
            <%= link_to book_path(@book2), method: :get do %>
              <%= @book2.title %>
            <% end %>
          </td>
          
          <td><%= @book2.body %></td>
          <% if @book2.user.id == current_user.id then %>
            <td><%= link_to "Edit", edit_book_path(@book2), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@book2), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: '本当に消しますか？' } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      </tbody>
    </table>

    </div>
  </div>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto mt-5">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <div class='px-3 mx-auto'>
      <h1>Welcome to <i class='fas fa-book'></i><strong>Bookers</strong>!!</h1>
    </div>
  </div>
</div>

<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/show.html.erb
<header>
  
</header>

app/views/homes/top.html.erb
<div class='container'>
  <div class="row">
    <div class="mx-auto col-11">
      <h1>welcome to <i class='fas fa-book'></i><strong>Bookers!!</strong></h1>
      <p>In <i class='fas fa-book'></i><strong>bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions ,<br>and emotions</p>
      <p>about various books!</p>
      <div class='btn-wrapper col-10 mx-auto'>
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expend-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to 'Bookers', '/', class: 'navbar-brand' %>
          <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to ' Home', user_path(current_user), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li>
              <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light', method: :delete %>
            </li>
          </ul>
        </div>
      </nav>
    <% else %>
      <nav class="navbar navbar-expend-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to 'Bookers', '/', class: 'navbar-brand' %>
          <ul class="navbar-nav ml-auto">
            <li>
               <%= link_to ' Home', root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to ' About', home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_user-info.html.erb
 <h2>User info</h2>
    <table class='table'>
      <tbody>
        <tr><%= attachment_image_tag user, :profile_image_id, :fill, 30, 30, fallback: "no_image.jpg" %><tr>
        <tr> <th>name</th> <th> <%= user.name %></th> </tr>
        <tr> <th>introduction</th> <th><%= user.introduction %></th> </tr>
      </tbody>
    </table>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block mb-3", method: :get do %>
    <i class="fas fa-user-cog"></i>
  <% end %>

app/views/users/edit.html.erb
<% if @user && @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="from-group">
          <h4>Name</h4>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <h4>Image</h4>
          <%= f.attachment_field :profile_image %>
        </div>

         <div class="field">
          <h4>Introduction</h4>
          <%= f.text_area :introduction %>
        </div>

        <div class="actions">
           <%= f.submit "Update User" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto mt-5">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<div class="container px-5 px-sm-o">
    <div class="row">
        <div class="col-md-3">
          <%= render 'users/user-info', user: @user %>
          <%= render 'books/form', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h1>Users</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= attachment_image_tag @user, :profile_image_id, :fill, 30, 30, fallback: "no_image.jpg" %></td>
                        <td><%= user.name %></td>
                        <td><%= link_to "Show", user_path(user.id) %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'users/user-info', user: @user %>
            <%= render 'books/form', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <th></th><th>Title</th><th>Opinion</th>
                </thead>
                <tbody>
                <% @books.each do |books| %>
                    <tr>
                        <td>
                            <%= link_to user_path(books.user.id), method: :get do %>
                            <%= attachment_image_tag books.user, :profile_image_id, :fill, 30, 30, fallback: "no_image.jpg" %>
                            <% end %>
                        </td>
                        <td><%= link_to books.title, book_path(books) %></td>
                        <td><%= books.body %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto mt-5">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>